# Generated by Django 5.0 on 2024-02-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicachievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/academics/'),
        ),
    ]
