# Generated by Django 5.0 on 2024-01-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='media/thumbnails/'),
            preserve_default=False,
        ),
    ]
