# Generated by Django 5.0 on 2024-01-09 02:19

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tinymce_content',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='ended_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='started_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
