# Generated by Django 5.0 on 2024-01-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_academicachievement_certification_volunteering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('design', 'ui.ux design'), ('graphics', 'graphics'), ('development', 'development')], default='design', max_length=255),
        ),
    ]
