# Generated by Django 5.0 on 2024-02-13 23:09

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_message_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
